
import numpy as np
from orphics import maps
from pixell import curvedsky as cs
import healpy as hp
import time
import argparse
import camb
import matplotlib.pyplot as plt
from pathlib import Path

parser = argparse.ArgumentParser(description='Generate Tau Sims, CMB*exp(-τ) sims, and CMB*exp(-τ) + WN Sims')
parser.add_argument("--nsims", type=int, default=1, help="Number of simulations to generate.")
parser.add_argument("--CMB", action='store_true',default=True,help='If true, then make CMB*exp(-τ) sims.')
parser.add_argument("--noise", action='store_true',default=True,help='If true, then make CMB*exp(-τ) + WN Sims.')
parser.add_argument("--noiselevel", type=float, default=15,help="Noiselevel in µK'")
parser.add_argument("--startind", type=int, default=1, help="First new simulation index you want to make.")
parser.add_argument("--lmax", type=int, default=3000, help="What is the maximum multipole you want to generate these simulations to?")
parser.add_argument("--savepath", type=str, help="Where are you saving your simulations?")
parser.add_argument("--nside", type=int, default=2048, help="What healpix resolution would you like to use?")

args = parser.parse_args()

nsims = args.nsims

lmax = args.lmax
l = np.linspace(0,lmax,lmax+1)

noiselevel=args.noiselevel

start_ind = args.startind

save_path = Path(args.savepath)
save_path.mkdir(parents=True, exist_ok=True)

nside = args.nside

########### load up CMB power spectrum from CAMB #################

pars = camb.CAMBparams()
pars.set_cosmology(H0=67.5, ombh2=0.022, omch2=0.122)
pars.InitPower.set_params(As=2.1e-9, ns=0.965)
pars.set_for_lmax(lmax, lens_potential_accuracy=1)

results = camb.get_results(pars)

cmb_ps = results.get_cmb_power_spectra(pars, CMB_unit="muK", raw_cl=True)["total"]

cl_tt = cmb_ps[:lmax + 1, 0]

# ########### Load up tau theory curve ################# 

"""This input optical-depth power spectrum is derived from a simulation generated by the publicly available AMBER pipeline (Trac et al. 2022)
    and is used to generate Gaussian realizations of the patchy optical-depth field based on given input reionization parameters.
    The parameters chosen for this power spectrum are as follows:
    midpoint reionization redshift, z_mid = 8
    middle 90% of the redshift duration of reionization, Δz = 4
    redshift asymmetry parameter, A_z = 3
    minimum halo mass required to produce ionizing radiation, M_min = 10^8 M_sun
    mean-free path of ionizing photons, λ = 3 Mpc/h"""

REPO_ROOT = Path(__file__).resolve().parents[1]
TAU_PATH = REPO_ROOT / "data" / "cl_tau.txt"

tau_ells, cl_tau = np.loadtxt(TAU_PATH, unpack=True, skiprows=1)

mask = tau_ells <= lmax

tau_ells_use = tau_ells[mask].astype(int)
cl_tau_use = cl_tau[mask]

cl_tau_full = np.zeros(lmax + 1)
cl_tau_full[tau_ells_use] = cl_tau_use

################# optional plot to check out the power spectrum, in log(y) axis to see the full shape: ################# 
# plt.figure()
# plt.title("τ power spectrum from fiducial AMBER model")
# plt.semilogy(tau_ells_use, cl_tau_use)
# plt.grid()
# plt.xlabel(r"$\ell$", fontsize=17)
# plt.ylabel(r"$C_\ell^{\tau \tau}$", fontsize=15)

################ make simulations and save ################# 

for i in range(start_ind, start_ind + nsims):

    sim_idx = f"{i:05d}"

    # make tau simulation from fiducial power spectrum and save it to disk for our check later
    taualm = cs.rand_alm(cl_tau_full, lmax=lmax)

    hp.write_alm(save_path / f"tau_alm_{sim_idx}.fits",
        taualm,
        overwrite=True)
    
    # make CMB sim, one TT and blank E and B
    cmbalm = cs.rand_alm(cl_tt, lmax=lmax)
    
    # move to real space to do the modulation so we don't need to convolve
    cmbmap = hp.alm2map(cmbalm, nside=nside)
    taumap = hp.alm2map(taualm, nside=nside)

    ####### Mod_T = T(n) * exp(-tau(n)) ##### 
    modcmb_map = cmbmap * np.exp(-taumap)
    #########################################

    modcmb_alm = hp.map2alm(modcmb_map, lmax=lmax)

    # make CMB sim, with white noise added
    # making 1 noise realization per simulation 

    # N_l = (Delta_T * pi / (180 * 60))^2 / B_l^2
    noise_ps = (noiselevel * np.pi / (180 * 60))**2 / maps.gauss_beam(l, 1.4)**2

    nalm = cs.rand_alm(noise_ps,lmax=lmax)
    
    modcmb_noisy_alm = np.add(modcmb_alm,nalm)

    # Save simulated screened + noisy CMB alm
    hp.write_alm(
        save_path / f"modulated_cmb_alm_{sim_idx}.fits",
        modcmb_noisy_alm,
        overwrite=True
    )